# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitlab.boxfish.cn/iOS/Specs.git'

inhibit_all_warnings!

def boxfishCommonPods

    pod 'AFNetworking', '~> 3.0'    
    pod 'MBProgressHUD', '~> 0.9'
    pod 'Fabric', '~> 1.7.0'
    pod 'FMDB', '~> 2.7'
    pod 'SDWebImage', '~> 3.7'
    pod 'SSZipArchive', '2.1.4'
    pod 'YYKit', '~> 1.0.9’
    pod 'Masonry', '~> 1.1.0'
    #极光推送
    pod 'JPush' , '~> 3.0.6'
    #友盟
    pod 'UMCCommon'
    pod 'UMCAnalytics'
    pod 'UMCShare/Social/WeChat', '~> 6.9'
    pod 'UMCShare/Social/QQ', '~> 6.9'
    pod 'UMCShare/Social/AlipayShare', '~> 6.9'
    pod 'MJRefresh', '~> 3.0.0'
    pod 'MJExtension', '~> 3.0.0'
    pod 'TZImagePickerController'
    
end


target 'AmazingCard' do
    boxfishCommonPods
end


